//This class represents an attendee of an event,
//it has properties for the attendee's name, email, and check-in status.
class Attendee {
  constructor(name, email) {
    this.name = name;
    this.email = email;
    this.checkedIn = false;
  }
}

//This class represents an event,
//it has properties for the event's id, name, date, and a list of attendees.
class Event {
  constructor(id, name, date) {
    this.id = id;
    this.name = name;
    this.date = date;
    this.attendees = [];
  }

  //This function registers an attendee for the event,
  //it checks for duplicate emails and throws an error if the email is already registered
  registerAttendee(name, email) {
    // Check for duplicate email
    const exists = this.attendees.find((a) => a.email === email);
    if (exists) {
      throw new Error("Email already registered for this event.");
    }

    const attendee = new Attendee(name, email);
    this.attendees.push(attendee);
  }

  //THis function checks in an attendee by their email,
  //if the email is not found it throws an error
  checkInAttendee(email) {
    const attendee = this.attendees.find((a) => a.email === email);

    if (!attendee) {
      throw new Error("Attendee not registered for this event.");
    }

    attendee.checkedIn = true;
  }

  //This function generates a report of the event, including total registered attendees,
  //total checked-in attendees, and a list of checked-in attendees with their names and emails.
  generateReport() {
    const totalRegistered = this.attendees.length;
    const checkedInList = this.attendees.filter((a) => a.checkedIn);
    const totalCheckedIn = checkedInList.length;

    return {
      eventName: this.name,
      totalRegistered,
      totalCheckedIn,
      checkedInAttendees: checkedInList.map((a) => ({
        name: a.name,
        email: a.email,
      })),
    };
  }

  //This function generates a console report based on the report generated by generateReport()
  generateConsoleReport() {
    const report = this.generateReport();

    console.log("Event:", report.eventName);
    console.log("Total Registered:", report.totalRegistered);
    console.log("Total Checked In:", report.totalCheckedIn);
    console.log("Checked-In Attendees:");

    report.checkedInAttendees.forEach((a) => {
      console.log(`- ${a.name} (${a.email})`);
    });
  }
}

//Adding an event
const event = new Event(1, "Tech Conference", "2026-04-10");

//Registering attendees
event.registerAttendee("Alice", "alice@email.com");
event.registerAttendee("Bob", "bob@email.com");

//Checking in attendees
event.checkInAttendee("alice@email.com");

//Generating a report
const report = event.generateReport();
event.generateConsoleReport();
